### DISCUSSION TITLE
Spice.ai Open Source 1.0-stable

### DISCUSSION THREAD

**Discussion by dennyglee** [unitycatalog/unitycatalog#876] [Show and tell]
Hey @lukekim - we're so excited about Spice.AI OSS 1.0!  Could you please chime in here to tell us more about this project?

**Comment by lukekim** [comment]
Thanks, @dennyglee!

<img width="740" alt="spice ai-compute-engine" src="https://github.com/user-attachments/assets/40c55404-803d-439c-a50b-bd2dee5d9d03" />

We’re excited to share how to unify data and models with Unity Catalog and the latest Spice.ai Open Source 1.0-stable release! For those who haven’t tried it yet, Spice.ai OSS is a portable compute engine written in Rust that provides low-latency data query, retrieval, and AI inference—for building data-grounded AI applications with hosted and local models. With the [Unity Catalog Catalog Connector](https://spiceai.org/docs/components/catalogs/unity-catalog), you can locally materialize and accelerate your Unity Catalog (or Databricks Unity Catalog) datasets using Arrow, DuckDB, or SQLite, then serve them to your applications or LLMs, in one unified engine.

We're using the Rust client `unitycatalog-rs` and `delta-kernel-rs` library.

Read the [Spice.ai Open Source 1.0 announcment](https://spiceai.org/blog/announcing-1.0-stable).

<img width="740" alt="Spice ai OSS as a data and AI compute engine over disaggregated storage" src="https://github.com/user-attachments/assets/c26481ae-94ce-4a17-a5e4-511103a54e53" />

For anyone who wants to get started, here’s a quick rundown:

## Installation

1. **Install Spice.ai OSS**  

Refer to the [Installation Docs](https://docs.spiceai.org/getting-started/installation) or simply run:
   
```bash
curl https://install.spiceai.org | /bin/bash
```
Or install via Homebrew:

```bash
brew install spiceai/spiceai/spice
```

3. **Create a new directory and initialize a Spicepod.yml**

```bash
mkdir uc_quickstart
cd uc_quickstart
spice init
```

## Query your Unity Catalog tables

1. **Add the Unity Catalog Connector**

In your spicepod.yaml, configure the connector to point to your Unity Catalog endpoint. For example:

```yaml
catalogs:
  - from: unity_catalog:https://<unity_catalog_host>/api/2.1/unity-catalog/catalogs/<catalog_name>
    name: uc_quickstart
    params:
      # AWS example
      unity_catalog_aws_access_key_id: ${env:AWS_ACCESS_KEY_ID}
      unity_catalog_aws_secret_access_key: ${env:AWS_SECRET_ACCESS_KEY}
      unity_catalog_aws_region: us-west-2
      unity_catalog_aws_endpoint: s3.us-west-2.amazonaws.com
```

2. **Start the Spice runtime**

```bash
spice run
```

In a separate terminal, launch the interactive SQL REPL:

```bash
spice sql
```

4. **Query your Unity Catalog tables**

```sql
SHOW TABLES;
-- Then query your table of interest
SELECT * FROM uc_quickstart.default.taxi_trips LIMIT 5;
```

### Chat with your Unity Catalog tables

1. **Add an LLM to your Spicepod**

In your `spicepod.yaml`, add a new model to the models section, for example:

```yaml
models:
  - from: openai:gpt-4o
    name: openai
    params:
      # Optionally store your OpenAI API key as an environment variable
      openai_api_key: ${env:SPICE_OPENAI_API_KEY}
      tools: auto
```

2. **Run Spice with your LLM**

Spice will now act as a gateway for your chosen model (OpenAI, Anthropic, Hugging Face, etc.). You can also [load and serve models like llama 3 locally](https://github.com/spiceai/cookbook/blob/trunk/llama/README.md).

3. **Use spice chat**

In a separate terminal, type:

```bash
spice chat
```

You’ll see a prompt where you can ask queries that combine your Unity Catalog data with the LLM. For example:

```console
chat> What datasets do I have access to?

You have access to the following dataset:

- **Table Name:** taxi_trips
- **Description:** Taxi trips data stored in Unity Catalog.
```

```console
chat> What's the largest tip a passenger gave?

The largest tip is $428.00
```

That’s it!

For more details, check out:

- The [Unity Catalog + Spice.ai OSS integration guide](https://github.com/unitycatalog/unitycatalog/blob/main/docs/integrations/unity-catalog-spiceai.md)
- The [Unity Catalog Connector Quickstart](https://docs.spiceai.org/catalogs/unitycatalog)
- The [Databricks Unity Catalog Connector Quickstart](https://docs.spiceai.org/catalogs/databricks_unitycatalog)
- The [Spice.ai OSS Cookbook](https://spiceai.org/cookbook)

Feel free to report any issues or feature requests on the Unity Catalog Slack, [GitHub](https://github.com/spiceai/spiceai), or swing by our [Discord](https://discord.gg/kZnTfneP5u)!
