### ISSUE TITLE
Define PROXY_HOST in ui Dockerfile using an environment variable

### ISSUE THREAD

**Issue by juandados** [unitycatalog/unitycatalog#1018]
When starting the docker container from the offical image, it assumes the UC server URL is "http://server", which is not always the case. It will be nice if we can specify this as an environment variable

An example when using docker compose like
```
  unitycatalog-server:
    image: unitycatalog/unitycatalog:latest
    ports:
      - "4040:4040"
     ...

  unitycatalog-ui:
    image: unitycatalog/unitycatalog-ui:main
    ports:
      - "3000:3000"
    depends_on:
      - unitycatalog-server
```

Will break as the official image is using the "server" default [Dockerfile](https://github.com/unitycatalog/unitycatalog/blob/aadc6fc6a47a9d70942417fa65d9c41378fab71e/ui/Dockerfile#L15)

Not sure if something like 

```
  unitycatalog-server:
    image: unitycatalog/unitycatalog:latest
    ports:
      - "4040:4040"
     ...

  unitycatalog-ui:
    image: unitycatalog/unitycatalog-ui:main
    ports:
      - "3000:3000"
    environment:
      - PROXY_HOST=http://unitycatalog-server
    depends_on:
      - unitycatalog-server
```

Is doable
